# Generated by Django 4.1.1 on 2022-09-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospedagen',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=630, max_digits=8),
            preserve_default=False,
        ),
    ]
