# Generated by Django 4.1.1 on 2022-09-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hospedagen_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospedagen',
            name='taxa_limpeza',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
