# Generated by Django 4.1.1 on 2022-09-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hospedagen_taxa_limpeza'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospedagen',
            name='preco_por',
            field=models.CharField(choices=[('D', 'Dia'), ('S', 'Semana'), ('M', 'Mês')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
