# Generated by Django 4.1.1 on 2022-09-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_hospedagen_preco_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospedagen',
            name='preco_por',
            field=models.CharField(choices=[('Dia', 'Dia'), ('Semana', 'Semana'), ('Mês', 'Mês')], default='Dia', max_length=6),
        ),
    ]
