# Generated by Django 4.1.1 on 2022-09-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_hospedagen_preco_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospedagen',
            name='imagem_4',
            field=models.ImageField(default=1, upload_to='foto/%y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospedagen',
            name='imagem_5',
            field=models.ImageField(default=1, upload_to='foto/%y/%m/%d'),
            preserve_default=False,
        ),
    ]
